{
  "data": {
    "GatewayError": {
      "Exception": "NotFound",
      "Message": "Object with id 43ebdc1f854f4e9f96592f32c00c7179 does not exist.",
      "Trace": [
        "Traceback (most recent call last):\n",
        "  File \"./ion/services/coi/service_gateway_service.py\", line 243, in process_gateway_request\n    result = methodToCall(**param_list)\n",
        "  File \"./interface/services/sa/iinstrument_management_service.py\", line 2938, in get_instrument_device_extension\n    return self.request(IonObject('instrument_management_get_instrument_device_extension_in', **{'instrument_device_id': instrument_device_id,'ext_associations': ext_associations or None,'ext_exclude': ext_exclude or None}), op='get_instrument_device_extension', headers=headers, timeout=timeout)\n",
        "  File \"./extern/pyon/pyon/net/endpoint.py\", line 986, in request\n    return RequestResponseClient.request(self, msg, headers=headers, timeout=timeout)\n",
        "  File \"./extern/pyon/pyon/net/endpoint.py\", line 806, in request\n    retval, headers = e.send(msg, headers=headers, timeout=timeout)\n",
        "  File \"./extern/pyon/pyon/net/endpoint.py\", line 133, in send\n    return self._send(_msg, _header, **kwargs)\n",
        "  File \"./extern/pyon/pyon/net/endpoint.py\", line 861, in _send\n    raise ex\n",
        "NotFound: 404 - Object with id 43ebdc1f854f4e9f96592f32c00c7179 does not exist.\n"
      ]
    }
  }
}